---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: database
    image: "{{ db_image }}"
    state: started
    restart_policy: always
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    networks:
      - name: app_network