# ansible/group_vars/all/vault.yml
postgres_db: db
postgres_user: usr
postgres_password: pwd

dockerhub_username: patriceipe

backend_image: "{{ dockerhub_username }}/tp-devops-backend:latest"
db_image: "{{ dockerhub_username }}/tp-devops-database:latest"
front_image: "{{ dockerhub_username }}/tp-devops-front:latest"
httpd_image: "{{ dockerhub_username }}/tp-devops-httpd:latest"

ssh_private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCwR8XNBOhnJQIZ
  eShXQzC7Dhy1zuKaPxsuoRQErCJhtyx/trPK8w3hYEywfsp7ReJQaXR/a0QhXCHF
  wacjVFAbRGB7sbRVjXWEiUzOCRGulCbQzEb1W22My1iZ9FfOjCb5T+HYTPgAUNGN
  +cDL33Jw9trtJj7g3n7oTrVxczH92zZFt6VGWKAxP1Bo2TSjUBXsAQ2Hj7UbLKHF
  RUkTdC1uvHgoT/JKLIU7I0kmfPPo9bXJyJi2E+7tytOJdhsmRw8EgFU5RDn+UTGb
  nGzseTh7Iza2br47/7R4b6wXheVU5ahAQjfTYBYQQebbXdpkb9sZxrrnvwj47Se1
  WUrwz95q5g20FwobdANgMRFxCnqpQ+j0NzhWMMj8p0eV8URBscq4an9MfxEhKwZ9
  O1u2YagZ4bUmaIvTOwPPkRGFXBr3WPLa/Ruo/xnYKUGkzvi6Tr3GcVkW2HUN5xcQ
  siwHGik3sGMDtxE5nc4faHzHw0izDx6eMPjkFaRkMyxxao7n+RIxjrftafpi92Ax
  mcKkLCh75ZyYo0O2TZTKi84QCL2+PC+MdwEXk1a/Z9WXDa1iTk+Tp+4v/dciPs2r
  6JjyZrDN2Av+sZM+kdw5joGF+ksSg5YXiCQszR39q3P4es6OqmfTKUYox2Lfrncp
  P91T2oOVakIwI36POlWD0ZY9TuqwVQIDAQABAoICADLyIz/r3bDFmNQ82ERT9lbx
  Lqn6pzHV8CirQ+pPx0X/Vtx4NIEAeq/6kV9m3WUAHvaHa7RRj2imxFnvbDsBKH+g
  5NOK2afqEJ8jwS9AnrwaNBefGhjZ+hC5ShuAawoWJkNia06EfB43PUDvf+FL7Dqq
  lT35ki2SEBJagQTPOpD31DkU6K6qeW2SM06CC7zxLcy9xye5CCnY3c3yBrsZFfJN
  hNp9tHPsZvre6Uq2zRU0QfwVvdDNdP2DY1x0ZkdLPRNbdYXt6mbOF2y2KiKzq/em
  hy71VYRok8NE3vMTbuJ41wXvPUwZFndPXIVkm/PwAd3yudy1MMYkYBgAvPBY2xoF
  3Pek8ruYfgs36butWm56VQttPG+fWQizVti3lul1aRk/7hr3C3mQ8EslV6FQCb6I
  nnbq9I0VIrO0SAqmS/77Do5a6V7tsBLoBZsje8qy/0VHYTyG3iMCP6tHAHj6/abO
  CcF22iz3mqb5Xa8Q/LBozqdzCiqtrt66WIEFNEiEyXvMAZpcBGIlaqti1t0uRBx7
  gePmgqP7fqWCfYgow6HjOL/SQOmsEbw0Ca3A9ThkivKn4AurgpH13QxmenHyHuYg
  CavtWav+j/3fIl1lzLYP43CJ7kFv7yhfTvaio7vrSw3xOzYN5yRMzv5gqHW63+pZ
  wERWojob7A1GylUHN09XAoIBAQDjXWPPN8jAmzE+H0Lw2/ovr/y8D+fpoD4XB8iW
  iaiDojFXRbfhS9ZUcKJrTt/5dgnkyltmj1iZ+ikZpmg2c+uZZHq81NMdZu3dm1ic
  CCQEEP+Y0ZkTgDCRtA0GkRFX5mIj7ifvVsSdeYUVkfTcHzSAjv9MaopDGNzmqVJE
  D2L1rCAhBgEqXHZE2oPYI5qzkzMFLPm24dV49ZK5rtfbcCQ/vM8u71k5bzecgG8q
  im/87KGBZ5mBbBCdXJn17HgurVgDEW5/0FRCW3ZGXmHzi3mTXWFQtI8ctJPzYLrM
  AwULKK+kYcdkEjJKSOs/HxHMHvWwhuX8Y4JiuDstoueWEgwjAoIBAQDGe1Zlzvos
  thY6kyQak/mI/mlwAlME41bKDMBdy5gWgSgeM66lZrnfmH74NZDg3aCAxA/3r/3M
  pmeEEOpquxtN8mOOYfbaaC8VfaOqqKcDjByP9HA32N4qlEQuELK9fPZpB7rvUJoh
  +9Xa2/NMbWZzfNK80v0t0WhROCnoBCmmnjZjXsD+4qvssNn+fnTVbWwviI8f3vuH
  lDWOFPBBF+g4ATDX503l8e8gkq0/dT2lViurlpAqoS48+GVGFwL6y3r7ftFhvexX
  b+OTm4OOKDhPoYr+fTOLmYFrebMn4wOcRgIqHBioIRdpXedloro4+SluXxo9ZkG4
  vCGg6+WQx70nAoIBACriLXYjFmlFnDcUXGLjir+92NR7x4koIS3k2O+TzUXurJHC
  Y5lJ3YYVrHzC5rm9isYtaKnidZqtNV1SJqvGl3RaIFBHb/5GsKywpTjgzDI8Jolj
  VxT3g7GnnSFU8Ul7+Zy/Sab53aG6DuDvo5h1BkkNL5fxLFzVbqzO2OZfZJHjwjeY
  U1XzFJeOA3ob1QzzwZbDUeItnD7xSphdIvePojanXQiEOnb7xChvjQggDllNJHUs
  3iYsBMI5egyJam2bYlNJ0WaoG4xcheVl3eG6t9aUsUswkyGd6Z3o67KZCzV8mgxO
  KPZ1/ChIsp44NPokCMEf4HcHKcuG5hqIdFe41bMCggEALr7fo0yy+RLNe3AqIaRW
  MeCRXpL9kHomd6G3MKABqtMyaqKLcGMYRcP5q2WaQIuSAKGsjQ5C/Q739E+zlf2J
  ObtrnR4PcHL3G92iTVA5PYmjNHhCcbS+5lJTGHJQVnZ25leuvCxEkNpqDIie7ZIa
  ffqY+2XJwR+/rNlIbV+Fm7tJXe/0DlO+YBlqzhhkVdvWjf9gjgYLQWwzjMn7p6kE
  xSPqp/7PBugLBKXm7bokEauQz3G/dHrPlAaAe5hx2DVSOqcskxOS9Sjh9WK8AiAQ
  2xhVzwgXurolk/Vur2c083o9ikNhvz9D70nxdKt1pnNwQZFecbWCpwqP9QF56LZS
  IwKCAQEAk6cW5duskqgniMkHVQoOazKOpMPbxDORxROoPHiSTEuqiirWs2w53epX
  VZF8hFkowYLmmq1/FkNTzsMVNm0ThvOj2ZTOhO+uFp6a9hTKWhXonzg6E8ZnWCTa
  oEJ84CKxbp4pl0T4MAUdooIyOz2Quc4B9LqqcdRW9fR0OiiYvBX1RfPl1uod9TPQ
  McIlNdJ/sCAGbQEz3cEHkyKT6ZqiO1Oqyi4GyFacv+3e/h9U/ppBboXB7HoKVUTz
  9MEdeka2SDv6Ea7N+5wJzYq0fWfrxSkoDwcHFnr6vmzwoqvEO0oxKKCzH9N7w7py
  BZHkHy6G8lhMnJo5niwmLzkD66UocA==
  -----END PRIVATE KEY-----

