---
# tasks file for roles/front
- name: Run frontend
  docker_container:
    name: front
    image: patriceipe/tp-devops-front:latest
    state: started
    restart_policy: always
    networks:
      - name: app_network