---
# tasks file for roles/front
- name: Run proxy
  docker_container:
    name: proxy
    image: ${{ dockerhub_username }}/tp-devops-httpd:latest
    state: started
    recreate: true
    pull: true
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: app_network