---
# tasks file for roles/proxy
- name: Run proxy
  docker_container:
    name: proxy
    image: "{{ httpd_image }}"
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: app_network