---
# tasks file for roles/front
- name: Run front
  docker_container:
    name: front
    image: "{{ front_image }}"
    state: started
    restart_policy: always
    networks:
      - name: app_network