name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Tests and Sonar"]
    types:
      - completed

jobs:
  build-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          --username ${{ secrets.DOCKERHUB_USERNAME }} \
          --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/simpleapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest

  build-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          --username ${{ secrets.DOCKERHUB_USERNAME }} \
          --password-stdin

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/Database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

  build-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          --username ${{ secrets.DOCKERHUB_USERNAME }} \
          --password-stdin

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/http-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest