name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Tests and Sonar"]
    types:
      - completed

jobs:

  build-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # Login DockerHub (stable)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build + push backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/simpleapi
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:v1.0.${{ github.run_number }}


  build-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build + push database
      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/Database
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:v1.0.${{ github.run_number }}


  build-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build + push httpd
      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./cours-devops/http-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:v1.0.${{ github.run_number }}